# 01 — Food CPI sub-indices: hierarchy, coverage and usability per tariff episode

Next step 2 in `CONTRIBUTING.md`. Questions:
1. Which food CPI sub-indices exist in table 18-10-0004-01, and over which dates? (D03)
2. Which are available by province, Ontario included? (D13)
3. Which have enough history before each tariff episode for a synthetic control, and data after it? (D05, D17)
4. Are the sub-indices fine enough to isolate tariffed products? (D05)

Data: `data/raw/` from `src/fetch_data.py`. Logic: `src/cpi_catalog.py`. Output: `data/processed/cpi_food_catalog.csv` (not versioned).
French labels come from the FR table, joined on StatCan member ids (D16).

In [1]:
import sys
from pathlib import Path
sys.path.insert(0, str(Path.cwd().parent / "src") if Path.cwd().name == "notebooks" else "src")
import pandas as pd
import cpi_catalog as C
pd.set_option("display.width", 200); pd.set_option("display.max_rows", 200); pd.set_option("display.max_colwidth", 70)

cat = C.build_catalog()
out = C.ROOT / "data" / "processed" / "cpi_food_catalog.csv"
out.parent.mkdir(parents=True, exist_ok=True)
cat.to_csv(out, index=False)
print(f"{len(cat)} food products (nodes of the 'Food' subtree) -> {out.relative_to(C.ROOT)}")
print("Last published month:", cat.end.max())

129 food products (nodes of the 'Food' subtree) -> data\processed\cpi_food_catalog.csv
Last published month: 2026-08

## 1. Hierarchy and national coverage

In [2]:
view = cat.assign(product=cat.depth.map(lambda d: "  " * d) + cat["product"])
view[["product", "base", "start", "end", "n_months", "n_geo", "is_leaf"]]

                                                                   product        base    start      end  n_months  n_geo  is_leaf
0                                                                     Food    2002=100  1949-01  2026-08       932     13    False
1                                               Food purchased from stores    2002=100  1961-01  2026-08       788     13    False
2                                                                     Meat    2002=100  1978-09  2026-08       576     13    False
3                                 Fresh or frozen meat (excluding poultry)    2002=100  1978-09  2026-08       576     13    False
4                                                     Fresh or frozen beef    2002=100  1971-01  2026-08       668     13    False
5                               Fresh or frozen beef hip cuts (202404=100)  202404=100  2024-04  2026-08        29      1     True
6                              Fresh or frozen beef loin cuts (202404=100)  202404=100  2024-04  2026-08        29      1     True
7                               Fresh or frozen beef rib cuts (202404=100)  202404=100  2024-04  2026-08        29      1     True
8                             Fresh or frozen beef chuck cuts (202404=100)  202404=100  2024-04  2026-08        29      1     True
9                                          Fresh stewing beef (202404=100)  202404=100  2024-04  2026-08        29      1     True
10                                Fresh or frozen ground beef (202404=100)  202404=100  2024-04  2026-08        29      1     True
11                                 Other fresh or frozen beef (202404=100)  202404=100  2024-04  2026-08        29      1     True
12                                                    Fresh or frozen pork    2002=100  1978-09  2026-08       576     13    False
13                             Fresh or frozen pork loin cuts (202404=100)  202404=100  2024-04  2026-08        29      1     True
14                         Fresh or frozen pork shoulder cuts (202404=100)  202404=100  2024-04  2026-08        29      1     True
15                                 Other fresh or frozen pork (202404=100)  202404=100  2024-04  2026-08        29      1     True
16                          Other fresh or frozen meat (excluding poultry)    2002=100  1985-01  2026-08       500      1     True
17                                                 Fresh or frozen poultry    2002=100  1949-01  2026-08       932     13    False
18                                                 Fresh or frozen chicken    2002=100  1949-01  2026-08       932     13    False
19                            Fresh or frozen chicken breasts (202404=100)  202404=100  2024-04  2026-08        29      1     True
20                             Fresh or frozen chicken thighs (202404=100)  202404=100  2024-04  2026-08        29      1     True
21                         Fresh or frozen chicken drumsticks (202404=100)  202404=100  2024-04  2026-08        29      1     True
22                              Fresh or frozen whole chicken (202404=100)  202404=100  2024-04  2026-08        29      1     True
23                              Other fresh or frozen chicken (202404=100)  202404=100  2024-04  2026-08        29      1     True
24                                           Other fresh or frozen poultry    2002=100  1961-01  2026-08       788      1     True
25                                                          Processed meat    2002=100  1985-01  2026-08       500     13    False
26                                                           Ham and bacon    2002=100  1985-01  2026-08       500      1    False
27                                                        Bacon (2013=100)    2013=100  2013-01  2026-08       164      1     True
28                                       Ham excluding deli ham (2013=100)    2013=100  2013-01  2026-08       164      1     True
29                                                    Other processed meat    2002=100  1985-01  2026-08       500      1     True
30                                 Fish, seafood and other marine products    2002=100  1985-01  2026-08       500     13    False
31                                                                    Fish    2002=100  1978-09  2026-08       576     13    False
32               Fresh or frozen fish (including portions and fish sticks)    2002=100  1985-01  2026-08       500      1     True
33                                         Canned and other preserved fish    2002=100  1978-09  2026-08       576      1    False
34                                                Canned salmon (2013=100)    2013=100  2013-01  2026-08       164      1     True
35                                                  Canned tuna (2013=100)    2013=100  2013-01  2026-08       164      1     True
36                                       Seafood and other marine products    2002=100  1978-09  2026-08       576      1    False
37                                           Shrimps and prawns (2013=100)    2013=100  2013-01  2026-08       164      1     True
38                                              Other shellfish (2013=100)    2013=100  2013-01  2026-08       164      1     True
39                                                 Dairy products and eggs    2002=100  1971-01  2026-08       668     13    False
40                                                          Dairy products    2002=100  1949-01  2026-08       932     13    False
41                                                              Fresh milk    2002=100  1949-01  2026-08       932     13    False
42                                                   Whole milk (2013=100)    2013=100  2013-01  2026-08       164      1     True
43                                                 Low-fat milk (2013=100)    2013=100  2013-01  2026-08       164      1     True
44                                                                  Butter    2002=100  1949-01  2026-08       932     13     True
45                                                                  Cheese    2002=100  1985-01  2026-08       500     13    False
46                                               Cheddar cheese (2013=100)    2013=100  2013-01  2026-08       164      1     True
47                                             Processed cheese (2013=100)    2013=100  2013-01  2026-08       164      1     True
48                                    Unripened or fresh cheese (2013=100)    2013=100  2013-01  2026-08       164      1     True
49                                            Mozzarella cheese (2013=100)    2013=100  2013-01  2026-08       164      1     True
50                                          Ice cream and related products    2002=100  1967-01  2026-08       716      1     True
51                                                    Other dairy products    2002=100  1985-01  2026-08       500      1     True
52                                                                    Eggs    2002=100  1961-01  2026-08       788     13     True
53                        Bakery and cereal products (excluding baby food)    2002=100  1949-01  2026-08       932     13    False
54                                                         Bakery products    2002=100  1971-01  2026-08       668     13    False
55                                                   Bread, rolls and buns    2002=100  1985-01  2026-08       500      1     True
56                                                    Cookies and crackers    2002=100  1985-01  2026-08       500      1    False
57                                    Crackers and crisp breads (2013=100)    2013=100  2013-01  2021-05       101      1     True
58                                   Cookies and sweet biscuits (2013=100)    2013=100  2013-01  2021-05       101      1     True
59                                                   Other bakery products    2002=100  1985-01  2026-08       500      1     True
60                                   Cereal products (excluding baby food)    2002=100  1985-01  2026-08       500     13    False
61                                               Rice and rice-based mixes    2002=100  1978-09  2026-08       576      1     True
62           Breakfast cereal and other cereal products (excluding baby...    2002=100  1949-01  2026-08       932      1     True
63                                                          Pasta products    2002=100  1978-09  2026-08       576      1    False
64                                           Dry or fresh pasta (2013=100)    2013=100  2013-01  2026-08       164      1     True
65                                                  Pasta mixes (2013=100)    2013=100  2013-01  2026-08       164      1     True
66                                             Flour and flour-based mixes    2002=100  1949-01  2026-08       932      1     True
67                                      Fruit, fruit preparations and nuts    2002=100  1978-09  2026-08       576     13    False
68                                                             Fresh fruit    2002=100  1949-01  2026-08       932     13    False
69                                                                  Apples    2002=100  1949-01  2026-08       932      1     True
70                                                                 Oranges    2002=100  1949-01  2026-08       932      1     True
71                                                                 Bananas    2002=100  1949-01  2026-08       932      1     True
72                                 Citrus (excluding oranges) (202304=100)  202304=100  2023-04  2026-08        41      1     True
73                                                     Grapes (202304=100)  202304=100  2023-04  2026-08        41      1     True
74                               Berries (including cherries) (202304=100)  202304=100  2023-04  2026-08        41      1     True
75                                                       Other fresh fruit    2002=100  1985-01  2026-08       500      1     True
76                                  Preserved fruit and fruit preparations    2002=100  1985-01  2026-08       500     13    False
77                                                            Fruit juices    2002=100  1985-01  2026-08       500      1     True
78                            Other preserved fruit and fruit preparations    2002=100  1985-01  2026-08       500      1    False
79                                                 Canned fruit (2013=100)    2013=100  2013-01  2026-08       164      1     True
80                               Jam, jelly and other preserves (2013=100)    2013=100  2013-01  2026-08       164      1     True
81                                   Dried and dehydrated fruit (2013=100)    2013=100  2013-01  2026-08       164      1     True
82                                                 Frozen fruit (2013=100)    2013=100  2013-01  2026-08       164      1     True
83                                                          Nuts and seeds    2002=100  1985-01  2026-08       500      1     True
84                                   Vegetables and vegetable preparations    2002=100  1978-09  2026-08       576     13    False
85                                                        Fresh vegetables    2002=100  1949-01  2026-08       932     13    False
86                                                                Potatoes    2002=100  1949-01  2026-08       932      1     True
87                                                                Tomatoes    2002=100  1949-01  2026-08       932      1     True
88                                                                 Lettuce    2002=100  1949-01  2026-08       932      1     True
89                                                    Carrots (202304=100)  202304=100  2023-04  2026-08        41      1     True
90                                                     Onions (202304=100)  202304=100  2023-04  2026-08        41      1     True
91                                                    Peppers (202304=100)  202304=100  2023-04  2026-08        41      1     True
92                                                   Cucumber (202304=100)  202304=100  2023-04  2026-08        41      1     True
93                                                  Mushrooms (202304=100)  202304=100  2023-04  2026-08        41      1     True
94                                                  Other fresh vegetables    2002=100  1985-01  2026-08       500      1     True
95                         Preserved vegetables and vegetable preparations    2002=100  1985-01  2026-08       500     13    False
96                                             Frozen and dried vegetables    2002=100  1985-01  2026-08       500      1     True
97                      Canned vegetables and other vegetable preparations    2002=100  1978-09  2026-08       576      1     True
98                         Other food products and non-alcoholic beverages    2002=100  1985-01  2026-08       500     13    False
99                                                 Sugar and confectionery    2002=100  1971-01  2026-08       668     13    False
100                                                        Sugar and syrup    2002=100  1985-01  2026-08       500      1     True
101                                                          Confectionery    2002=100  1985-01  2026-08       500      1     True
102                                                   Edible fats and oils    2002=100  1978-09  2026-08       576     13    False
103                                                              Margarine    2002=100  1961-01  2026-08       788      1     True
104                                             Other edible fats and oils    2002=100  1973-04  2026-08       641      1     True
105                                                         Coffee and tea    2002=100  1971-01  2026-08       668     13    False
106                                                                 Coffee    2002=100  1978-09  2026-08       576      1    False
107                                    Roasted or ground coffee (2013=100)    2013=100  2013-01  2026-08       164      1     True
108                                    Instant and other coffee (2013=100)    2013=100  2013-01  2026-08       164      1     True
109                                                                    Tea    2002=100  1961-01  2026-08       788      1     True
110                                        Condiments, spices and vinegars    2002=100  1978-09  2026-08       576      1    False
111                             Fermented or pickled vegetables (2013=100)    2013=100  2013-01  2021-05       101      1     True
112                                 Sauces, condiments and dips (2013=100)    2013=100  2013-01  2021-05       101      1     True
113                                Herbs, spices and seasonings (2013=100)    2013=100  2013-01  2021-05       101      1     True
114                                                Other food preparations    2002=100  1978-09  2026-08       576      1    False
115                                                                   Soup    2002=100  1978-09  2026-08       576      1     True
116                                                             Baby foods    2002=100  1978-09  2026-08       576      1    False
117                               Canned infant or junior foods (2013=100)    2013=100  2013-01  2026-08       164      1     True
118                                              Infant formula (2013=100)    2013=100  2013-01  2026-08       164      1     True
119                                               Frozen food preparations    2002=100  1978-09  2026-08       576      1     True
120                                            All other food preparations    2002=100  1985-01  2026-08       500      1    False
121                                                  Nut butter (2013=100)    2013=100  2013-01  2026-08       164      1     True
122                Potato chips and other snack products n.e.c. (2013=100)    2013=100  2013-01  2026-08       164      1     True
123                   All other miscellaneous food preparations (2013=100)    2013=100  2013-01  2026-08       164      1     True
124                                                Non-alcoholic beverages    2002=100  1961-01  2026-08       788     13     True
125                                        Food purchased from restaurants    2002=100  1961-01  2026-08       788     13    False
126                          Food purchased from table-service restaurants    2002=100  1985-01  2026-08       500      1     True
127                 Food purchased from fast food and take-out restaurants    2002=100  1985-01  2026-08       500      1     True
128                   Food purchased from cafeterias and other restaurants    2002=100  1994-12  2026-08       381      1     True

## 2. Coverage by index base

StatCan adds detailed series over time with their own base period (for example `2013=100`, `202304=100`). The base tells when a series starts.

In [3]:
by_base = (cat.groupby("base")
           .agg(n=("product", "size"), first_start=("start", "min"), last_start=("start", "max"),
                ended_before_latest=("end", lambda e: (e < cat.end.max()).sum()), max_geo=("n_geo", "max"))
           .sort_values("first_start"))
by_base

             n first_start last_start  ended_before_latest  max_geo
base
2002=100    76     1949-01    1994-12                    0       13
2013=100    30     2013-01    2013-01                    5        1
202304=100   8     2023-04    2023-04                    0        1
202404=100  15     2024-04    2024-04                    0        1

In [4]:
print("Series discontinued before the latest month:")
cat.loc[cat.end < cat.end.max(), ["product", "base", "start", "end"]]

Series discontinued before the latest month:

                                        product      base    start      end
57         Crackers and crisp breads (2013=100)  2013=100  2013-01  2021-05
58        Cookies and sweet biscuits (2013=100)  2013=100  2013-01  2021-05
111  Fermented or pickled vegetables (2013=100)  2013=100  2013-01  2021-05
112      Sauces, condiments and dips (2013=100)  2013=100  2013-01  2021-05
113     Herbs, spices and seasonings (2013=100)  2013=100  2013-01  2021-05

## 3. Provincial availability (D13)

In [5]:
prov = cat[cat.n_geo > 1]
print(f"{len(prov)} of {len(cat)} food series are published below the national level; all include Ontario: {prov.has_ontario.all()}")
print("Their base periods:", prov.base.unique().tolist())
prov[["product", "start", "n_geo"]]

32 of 129 food series are published below the national level; all include Ontario: True
Their base periods: ['2002=100']

                                              product    start  n_geo
0                                                Food  1949-01     13
1                          Food purchased from stores  1961-01     13
2                                                Meat  1978-09     13
3            Fresh or frozen meat (excluding poultry)  1978-09     13
4                                Fresh or frozen beef  1971-01     13
12                               Fresh or frozen pork  1978-09     13
17                            Fresh or frozen poultry  1949-01     13
18                            Fresh or frozen chicken  1949-01     13
25                                     Processed meat  1985-01     13
30            Fish, seafood and other marine products  1985-01     13
31                                               Fish  1978-09     13
39                            Dairy products and eggs  1971-01     13
40                                     Dairy products  1949-01     13
41                                         Fresh milk  1949-01     13
44                                             Butter  1949-01     13
45                                             Cheese  1985-01     13
52                                               Eggs  1961-01     13
53   Bakery and cereal products (excluding baby food)  1949-01     13
54                                    Bakery products  1971-01     13
60              Cereal products (excluding baby food)  1985-01     13
67                 Fruit, fruit preparations and nuts  1978-09     13
68                                        Fresh fruit  1949-01     13
76             Preserved fruit and fruit preparations  1985-01     13
84              Vegetables and vegetable preparations  1978-09     13
85                                   Fresh vegetables  1949-01     13
95    Preserved vegetables and vegetable preparations  1985-01     13
98    Other food products and non-alcoholic beverages  1985-01     13
99                            Sugar and confectionery  1971-01     13
102                              Edible fats and oils  1978-09     13
105                                    Coffee and tea  1971-01     13
124                           Non-alcoholic beverages  1961-01     13
125                   Food purchased from restaurants  1961-01     13

In [6]:
# Which geographies publish the 'Food' index?
cpi = C.read_statcan("cpi_monthly", columns=["REF_DATE", "GEO", "Products and product groups", "UOM", "VALUE"])
food = cpi[(cpi["product"] == "Food") & (cpi.UOM == "2002=100")]
food.groupby("GEO").REF_DATE.agg(["min", "max"])

                                        min      max
GEO
Alberta                             1978-09  2026-08
British Columbia                    1978-09  2026-08
Canada                              1949-01  2026-08
Manitoba                            1978-09  2026-08
New Brunswick                       1978-09  2026-08
Newfoundland and Labrador           1978-09  2026-08
Nova Scotia                         1978-09  2026-08
Ontario                             1978-09  2026-08
Prince Edward Island                1978-09  2026-08
Quebec                              1978-09  2026-08
Saskatchewan                        1978-09  2026-08
Whitehorse, Yukon                   1982-03  2026-08
Yellowknife, Northwest Territories  1982-03  2026-08

## 4. Usability per tariff episode (D17)

A series is usable for an episode once it has at least `MIN_PRE_MONTHS` = 36 months before the first tariff month (`_pre_ok`) and at least one month after it (`_post` > 0).
Episodes come from `data/reference/tariff_events.csv`.

In [7]:
events = pd.read_csv(C.TARIFF_EVENTS)
rows = []
for ev in events.itertuples():
    pre_ok = cat[f"{ev.event_id}_pre_ok"]
    post = cat[f"{ev.event_id}_post"] > 0
    rows.append({"episode": ev.event_id, "start": ev.start_date, "pre_ok": pre_ok.sum(),
                 "post_available": post.sum(), "usable_now": (pre_ok & post).sum(),
                 "leaves_usable_now": (pre_ok & post & cat.is_leaf).sum()})
pd.DataFrame(rows)

  episode       start  pre_ok  post_available  usable_now  leaves_usable_now
0  CA2018  2018-07-01     106             129         106                 66
1  CA2025  2025-03-04     106             124         101                 61
2  CA2026  2026-09-08     114               0           0                  0

In [8]:
print("Series NOT usable for 2025 because they start too late (too little history):")
cat.loc[~cat.CA2025_pre_ok, ["product", "base", "start", "CA2025_pre"]]

Series NOT usable for 2025 because they start too late (too little history):

                                            product        base    start  CA2025_pre
5        Fresh or frozen beef hip cuts (202404=100)  202404=100  2024-04          11
6       Fresh or frozen beef loin cuts (202404=100)  202404=100  2024-04          11
7        Fresh or frozen beef rib cuts (202404=100)  202404=100  2024-04          11
8      Fresh or frozen beef chuck cuts (202404=100)  202404=100  2024-04          11
9                   Fresh stewing beef (202404=100)  202404=100  2024-04          11
10         Fresh or frozen ground beef (202404=100)  202404=100  2024-04          11
11          Other fresh or frozen beef (202404=100)  202404=100  2024-04          11
13      Fresh or frozen pork loin cuts (202404=100)  202404=100  2024-04          11
14  Fresh or frozen pork shoulder cuts (202404=100)  202404=100  2024-04          11
15          Other fresh or frozen pork (202404=100)  202404=100  2024-04          11
19     Fresh or frozen chicken breasts (202404=100)  202404=100  2024-04          11
20      Fresh or frozen chicken thighs (202404=100)  202404=100  2024-04          11
21  Fresh or frozen chicken drumsticks (202404=100)  202404=100  2024-04          11
22       Fresh or frozen whole chicken (202404=100)  202404=100  2024-04          11
23       Other fresh or frozen chicken (202404=100)  202404=100  2024-04          11
72          Citrus (excluding oranges) (202304=100)  202304=100  2023-04          23
73                              Grapes (202304=100)  202304=100  2023-04          23
74        Berries (including cherries) (202304=100)  202304=100  2023-04          23
89                             Carrots (202304=100)  202304=100  2023-04          23
90                              Onions (202304=100)  202304=100  2023-04          23
91                             Peppers (202304=100)  202304=100  2023-04          23
92                            Cucumber (202304=100)  202304=100  2023-04          23
93                           Mushrooms (202304=100)  202304=100  2023-04          23

## 5. Granularity for the 2026 dairy and cheese tariffs (D05)

The September 2026 tariffs target dairy (50%) and cheeses (25%) [R7, R8]. Which series cover them, and at which level?

In [9]:
dairy = cat[cat.parent.isin(["Dairy products", "Fresh milk", "Cheese"]) | cat["product"].isin(["Dairy products"])]
dairy[["product", "product_fr", "base", "start", "n_geo", "CA2026_pre", "CA2026_pre_ok", "CA2026_post"]]

                                 product                                      product_fr      base    start  n_geo  CA2026_pre  CA2026_pre_ok  CA2026_post
40                        Dairy products                               Produits laitiers  2002=100  1949-01     13         932           True            0
41                            Fresh milk                                      Lait frais  2002=100  1949-01     13         932           True            0
42                 Whole milk (2013=100)                          Lait entier (2013=100)  2013=100  2013-01      1         164           True            0
43               Low-fat milk (2013=100)      Lait faible en matières grasses (2013=100)  2013=100  2013-01      1         164           True            0
44                                Butter                                          Beurre  2002=100  1949-01     13         932           True            0
45                                Cheese                                         Fromage  2002=100  1985-01     13         500           True            0
46             Cheddar cheese (2013=100)                      Fromage cheddar (2013=100)  2013=100  2013-01      1         164           True            0
47           Processed cheese (2013=100)                        Fromage fondu (2013=100)  2013=100  2013-01      1         164           True            0
48  Unripened or fresh cheese (2013=100)  Fromage non affiné ou fromage frais (2013=100)  2013=100  2013-01      1         164           True            0
49          Mozzarella cheese (2013=100)                   Fromage mozzarella (2013=100)  2013=100  2013-01      1         164           True            0
50        Ice cream and related products               Crème glacée et produits connexes  2002=100  1967-01      1         716           True            0
51                  Other dairy products                        Autres produits laitiers  2002=100  1985-01      1         500           True            0

## 6. Findings

Written up in the decision log (D13 update, D17). See the text below each table for the numbers.